# This workflow is set up to be manually triggered via the GitHub Action tab.
# Given a version, it will tag those backend and webserver images as "latest".

name: Tag Latest Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version (ie v0.0.1) to tag as latest"
        required: true

permissions:
  contents: read

jobs:
  tag:
    # See https://runs-on.com/runners/linux/
    # use a lower powered instance since this just does i/o to docker hub
    runs-on: [runs-on, runner=2cpu-linux-x64, "run-id=${{ github.run_id }}-tag"]
    timeout-minutes: 45
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # ratchet:docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # ratchet:docker/login-action@v4.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Enable Docker CLI experimental features
        run: echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV

      - name: Pull, Tag and Push Web Server Image
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          docker buildx imagetools create -t aethersearch/aethersearch-web-server:latest aethersearch/aethersearch-web-server:${VERSION}

      - name: Pull, Tag and Push API Server Image
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          docker buildx imagetools create -t aethersearch/aethersearch-backend:latest aethersearch/aethersearch-backend:${VERSION}

      - name: Pull, Tag and Push Model Server Image
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          docker buildx imagetools create -t aethersearch/aethersearch-model-server:latest aethersearch/aethersearch-model-server:${VERSION}
